adb shell cmd package install-existing com.android.backupconfirm
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.bluetoothmidiservice
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.cellbroadcastreceiver
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.htmlviewer
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.blockednumber
adb shell cmd package install-existing com.android.statementservice
adb shell cmd package install-existing com.android.wallpaperbackup
adb shell cmd package install-existing com.debug.loggerui
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.marvin.talkback
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.lenovo.EngineeringCode
adb shell cmd package install-existing com.lenovo.dsa
adb shell cmd package install-existing com.lenovo.lsf
adb shell cmd package install-existing com.lenovo.lsf.device
adb shell cmd package install-existing com.lenovo.ocpl
adb shell cmd package install-existing com.lenovo.ue.device
adb shell cmd package install-existing com.lmsa.app.lmsapad
adb shell cmd package install-existing com.mediatek.duraspeed
adb shell cmd package install-existing com.mediatek.gnssdebugreport
adb shell cmd package install-existing com.mediatek.lbs.em2.ui
adb shell cmd package install-existing com.mediatek.mdmconfig
adb shell cmd package install-existing com.mediatek.mdmlsample
adb shell cmd package install-existing com.mediatek.omacp
adb shell cmd package install-existing com.tblenovo.center
adb shell cmd package install-existing com.tblenovo.setup
adb shell cmd package install-existing com.tblenovo.wallpaper
adb shell cmd package install-existing com.tbsmart.levision
adb shell cmd package install-existing com.wapi.wapicertmanager