adb shell pm uninstall --user 0 com.android.backupconfirm
adb shell pm uninstall --user 0 com.android.bips
adb shell pm uninstall --user 0 com.android.bluetoothmidiservice
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.android.carrierdefaultapp
adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.android.cts.ctsshim
adb shell pm uninstall --user 0 com.android.cts.priv.ctsshim
adb shell pm uninstall --user 0 com.android.dynsystem
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.android.htmlviewer
adb shell pm uninstall --user 0 com.android.managedprovisioning
adb shell pm uninstall --user 0 com.android.providers.blockednumber
adb shell pm uninstall --user 0 com.android.statementservice
adb shell pm uninstall --user 0 com.android.wallpaperbackup
adb shell pm uninstall --user 0 com.debug.loggerui
adb shell pm uninstall --user 0 com.google.android.apps.restore
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.lenovo.EngineeringCode
adb shell pm uninstall --user 0 com.lenovo.dsa
adb shell pm uninstall --user 0 com.lenovo.lsf
adb shell pm uninstall --user 0 com.lenovo.lsf.device
adb shell pm uninstall --user 0 com.lenovo.ocpl
adb shell pm uninstall --user 0 com.lenovo.ue.device
adb shell pm uninstall --user 0 com.lmsa.app.lmsapad
adb shell pm uninstall --user 0 com.mediatek.duraspeed
adb shell pm uninstall --user 0 com.mediatek.gnssdebugreport
adb shell pm uninstall --user 0 com.mediatek.lbs.em2.ui
adb shell pm uninstall --user 0 com.mediatek.mdmconfig
adb shell pm uninstall --user 0 com.mediatek.mdmlsample
adb shell pm uninstall --user 0 com.mediatek.omacp
adb shell pm uninstall --user 0 com.tblenovo.center
adb shell pm uninstall --user 0 com.tblenovo.setup
adb shell pm uninstall --user 0 com.tblenovo.wallpaper
adb shell pm uninstall --user 0 com.tbsmart.levision
adb shell pm uninstall --user 0 com.wapi.wapicertmanager