adb shell cmd package install-existing android.autoinstalls.config.oneplus
adb shell cmd package install-existing com.android.bluetoothmidiservice
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.simappdialog
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.coloros.activation
adb shell cmd package install-existing com.coloros.assistantscreen
adb shell cmd package install-existing com.coloros.bootreg
adb shell cmd package install-existing com.coloros.childrenspace
adb shell cmd package install-existing com.coloros.floatassistant
adb shell cmd package install-existing com.coloros.operationManual
adb shell cmd package install-existing com.coloros.scenemode
adb shell cmd package install-existing com.coloros.smartsidebar
adb shell cmd package install-existing com.coloros.systemclone
adb shell cmd package install-existing com.coloros.weather.service
adb shell cmd package install-existing com.fido.asm
adb shell cmd package install-existing com.fido.fido2client
adb shell cmd package install-existing com.fido.uafclient
adb shell cmd package install-existing com.google.android.adservices.api
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.googleassistant
adb shell cmd package install-existing com.google.android.apps.nbu.files
adb shell cmd package install-existing com.google.android.apps.photos
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.wellbeing
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.marvin.talkback
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.ar.lens
adb shell cmd package install-existing com.google.mainline.adservices
adb shell cmd package install-existing com.google.mainline.telemetry
adb shell cmd package install-existing com.heytap.accessory
adb shell cmd package install-existing com.heytap.colorfulengine
adb shell cmd package install-existing com.heytap.mcs
adb shell cmd package install-existing com.mediatek.omacp
adb shell cmd package install-existing com.netflix.mediaclient
adb shell cmd package install-existing com.netflix.partner.activation
adb shell cmd package install-existing com.oma.dm.sdm
adb shell cmd package install-existing com.oma.dm.sub
adb shell cmd package install-existing com.oneplus.account
adb shell cmd package install-existing com.oneplus.membership
adb shell cmd package install-existing com.oneplus.opbackup
adb shell cmd package install-existing com.oplus.aiunit
adb shell cmd package install-existing com.oplus.apprecover
adb shell cmd package install-existing com.oplus.atlas
adb shell cmd package install-existing com.oplus.bttestmode
adb shell cmd package install-existing com.oplus.crashbox
adb shell cmd package install-existing com.oplus.eid
adb shell cmd package install-existing com.oplus.encryption
adb shell cmd package install-existing com.oplus.engineercamera
adb shell cmd package install-existing com.oplus.engineermode
adb shell cmd package install-existing com.oplus.engineernetwork
adb shell cmd package install-existing com.oplus.games
adb shell cmd package install-existing com.oplus.healthservice
adb shell cmd package install-existing com.oplus.interconnectcollectkit
adb shell cmd package install-existing com.oplus.lfeh
adb shell cmd package install-existing com.oplus.linker
adb shell cmd package install-existing com.oplus.location
adb shell cmd package install-existing com.oplus.locationproxy
adb shell cmd package install-existing com.oplus.logkit
adb shell cmd package install-existing com.oplus.melody
adb shell cmd package install-existing com.oplus.metis
adb shell cmd package install-existing com.oplus.multiapp
adb shell cmd package install-existing com.oplus.nas
adb shell cmd package install-existing com.oplus.ndsf
adb shell cmd package install-existing com.oplus.nhs
adb shell cmd package install-existing com.oplus.obrain
adb shell cmd package install-existing com.oplus.ocloud
adb shell cmd package install-existing com.oplus.ocs
adb shell cmd package install-existing com.oplus.olc
adb shell cmd package install-existing com.oplus.omoji
adb shell cmd package install-existing com.oplus.onet
adb shell cmd package install-existing com.oplus.onetrace
adb shell cmd package install-existing com.oplus.postmanservice
adb shell cmd package install-existing com.oplus.qualityprotect
adb shell cmd package install-existing com.oplus.safecenter
adb shell cmd package install-existing com.oplus.sauhelper
adb shell cmd package install-existing com.oplus.securitypermission
adb shell cmd package install-existing com.oplus.sos
adb shell cmd package install-existing com.oplus.statistics.rom
adb shell cmd package install-existing com.oplus.synergy
adb shell cmd package install-existing com.oplus.trafficmonitor
adb shell cmd package install-existing com.oplus.viewtalk
adb shell cmd package install-existing com.oplus.virtualcomm
adb shell cmd package install-existing com.oplus.wifitest
adb shell cmd package install-existing com.oppo.quicksearchbox
adb shell cmd package install-existing com.qti.dcf
adb shell cmd package install-existing com.qti.qcc
adb shell cmd package install-existing com.qti.qualcomm.datastatusnotification
adb shell cmd package install-existing com.qualcomm.atfwd
adb shell cmd package install-existing com.qualcomm.embms
adb shell cmd package install-existing com.qualcomm.qcrilmsgtunnel
adb shell cmd package install-existing com.qualcomm.qti.dynamicddsservice
adb shell cmd package install-existing com.qualcomm.qti.ims
adb shell cmd package install-existing com.qualcomm.qti.lpa
adb shell cmd package install-existing com.qualcomm.qti.modemtestmode
adb shell cmd package install-existing com.qualcomm.qti.remoteSimlockAuth
adb shell cmd package install-existing com.qualcomm.qti.uim
adb shell cmd package install-existing com.qualcomm.qti.uimGbaApp
adb shell cmd package install-existing com.qualcomm.qti.xrcb
adb shell cmd package install-existing com.qualcomm.qti.xrvd.service
adb shell cmd package install-existing com.qualcomm.uimremoteclient
adb shell cmd package install-existing com.qualcomm.uimremoteserver
adb shell cmd package install-existing com.quicinc.voice.activation
adb shell cmd package install-existing com.ses.entitlement.o2
adb shell cmd package install-existing com.wapi.wapicertmanage
adb shell cmd package install-existing net.oneplus.weather
pause