adb shell pm uninstall -k --user 0 android.autoinstalls.config.lge.cct
adb shell pm uninstall -k --user 0 com.android.LGSetupWizard
adb shell pm uninstall -k --user 0 com.android.backupconfirm
adb shell pm uninstall -k --user 0 com.android.bips
adb shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb shell pm uninstall -k --user 0 com.android.calllogbackup
adb shell pm uninstall -k --user 0 com.android.carrierconfig
adb shell pm uninstall -k --user 0 com.android.carrierdefaultapp
adb shell pm uninstall -k --user 0 com.android.companiondevicemanager
adb shell pm uninstall -k --user 0 com.android.cts.ctsshim
adb shell pm uninstall -k --user 0 com.android.cts.priv.ctsshim
adb shell pm uninstall -k --user 0 com.android.egg
adb shell pm uninstall -k --user 0 com.android.gallery3d
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.tgoogle
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall -k --user 0 com.android.htmlviewer
adb shell pm uninstall -k --user 0 com.android.managedprovisioning
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.android.providers.blockednumber
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 com.android.stk
adb shell pm uninstall -k --user 0 com.android.traceur
adb shell pm uninstall -k --user 0 com.crucialsoft.asm
adb shell pm uninstall -k --user 0 com.crucialsoft.fido.client
adb shell pm uninstall -k --user 0 com.crucialtec.uaf
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.sheets
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.slides
adb shell pm uninstall -k --user 0 com.google.android.apps.nbu.files
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.apps.restore
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.google.android.apps.turbo
adb shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall -k --user 0 com.google.android.apps.work.oobconfig
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb shell pm uninstall -k --user 0 com.google.android.backuptransport
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb shell pm uninstall -k --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall -k --user 0 com.google.android.partnersetup
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall -k --user 0 com.google.android.setupwizard
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.ipsec.profile
adb shell pm uninstall -k --user 0 com.ipsec.service
adb shell pm uninstall -k --user 0 com.ipsec.vpnclient
adb shell pm uninstall -k --user 0 com.lge.LGSetupView
adb shell pm uninstall -k --user 0 com.lge.android.atservice
adb shell pm uninstall -k --user 0 com.lge.appbox.client
adb shell pm uninstall -k --user 0 com.lge.appbox.installer
adb shell pm uninstall -k --user 0 com.lge.bnr
adb shell pm uninstall -k --user 0 com.lge.camera.sticker.res
adb shell pm uninstall -k --user 0 com.lge.cic.eden.service
adb shell pm uninstall -k --user 0 com.lge.cloudhub
adb shell pm uninstall -k --user 0 com.lge.diag
adb shell pm uninstall -k --user 0 com.lge.diag.echolocate
adb shell pm uninstall -k --user 0 com.lge.effect
adb shell pm uninstall -k --user 0 com.lge.ellievision
adb shell pm uninstall -k --user 0 com.lge.entitlementcheckservice
adb shell pm uninstall -k --user 0 com.lge.eula
adb shell pm uninstall -k --user 0 com.lge.eulaprovider
adb shell pm uninstall -k --user 0 com.lge.gallery.collagewallpaper
adb shell pm uninstall -k --user 0 com.lge.gallery.vr.wallpaper
adb shell pm uninstall -k --user 0 com.lge.gametuner
adb shell pm uninstall -k --user 0 com.lge.gcuv
adb shell pm uninstall -k --user 0 com.lge.gdec.client
adb shell pm uninstall -k --user 0 com.lge.gnss.airtest
adb shell pm uninstall -k --user 0 com.lge.gnsslogsetting
adb shell pm uninstall -k --user 0 com.lge.gnsspostest
adb shell pm uninstall -k --user 0 com.lge.gnsstest
adb shell pm uninstall -k --user 0 com.lge.hifirecorder
adb shell pm uninstall -k --user 0 com.lge.hotspotprovision
adb shell pm uninstall -k --user 0 com.lge.ia.task.informant
adb shell pm uninstall -k --user 0 com.lge.ia.task.smartcare
adb shell pm uninstall -k --user 0 com.lge.icecontacts
adb shell pm uninstall -k --user 0 com.lge.ime
adb shell pm uninstall -k --user 0 com.lge.ime.solution.handwriting
adb shell pm uninstall -k --user 0 com.lge.ime.solution.text
adb shell pm uninstall -k --user 0 com.lge.ime.solution.tshanja
adb shell pm uninstall -k --user 0 com.lge.laot
adb shell pm uninstall -k --user 0 com.lge.launcher2.theme.optimus
adb shell pm uninstall -k --user 0 com.lge.leccp
adb shell pm uninstall -k --user 0 com.lge.lgcontentsetting
adb shell pm uninstall -k --user 0 com.lge.lgfota.permission
adb shell pm uninstall -k --user 0 com.lge.lgmapui
adb shell pm uninstall -k --user 0 com.lge.lgworld
adb shell pm uninstall -k --user 0 com.lge.phonemanagement
adb shell pm uninstall -k --user 0 com.lge.privacylock
adb shell pm uninstall -k --user 0 com.lge.qlens
adb shell pm uninstall -k --user 0 com.lge.qmemoplus
adb shell pm uninstall -k --user 0 com.lge.quicktools
adb shell pm uninstall -k --user 0 com.lge.rctprovider
adb shell pm uninstall -k --user 0 com.lge.servicemenu
adb shell pm uninstall -k --user 0 com.lge.sizechangable.weather
adb shell pm uninstall -k --user 0 com.lge.sizechangable.weather.platform
adb shell pm uninstall -k --user 0 com.lge.sizechangable.weather.theme.optimus
adb shell pm uninstall -k --user 0 com.lge.smartdoctor.webview
adb shell pm uninstall -k --user 0 com.lge.smartenabler
adb shell pm uninstall -k --user 0 com.lge.smartshare
adb shell pm uninstall -k --user 0 com.lge.smartshare.provider
adb shell pm uninstall -k --user 0 com.lge.smartsharepush
adb shell pm uninstall -k --user 0 com.lge.springcleaning
adb shell pm uninstall -k --user 0 com.lge.srtc
adb shell pm uninstall -k --user 0 com.lge.sui.widget
adb shell pm uninstall -k --user 0 com.lge.sync
adb shell pm uninstall -k --user 0 com.lge.systemservice
adb shell pm uninstall -k --user 0 com.lge.ticntool
adb shell pm uninstall -k --user 0 com.lge.updatecenter
adb shell pm uninstall -k --user 0 com.lge.video.vr.wallpaper
adb shell pm uninstall -k --user 0 com.lge.videostudio
adb shell pm uninstall -k --user 0 com.lge.vrplayer
adb shell pm uninstall -k --user 0 com.lge.wifihotspotwidget
adb shell pm uninstall -k --user 0 com.qualcomm.qcrilmsgtunnel
adb shell pm uninstall -k --user 0 com.qualcomm.qti.dynamicddsservice
adb shell pm uninstall -k --user 0 com.qualcomm.qti.poweroffalarm
adb shell pm uninstall -k --user 0 com.qualcomm.qti.qmmi
adb shell pm uninstall -k --user 0 com.qualcomm.qti.qms.service.trustzoneaccess
adb shell pm uninstall -k --user 0 com.qualcomm.qti.remoteSimlockAuth
adb shell pm uninstall -k --user 0 com.qualcomm.qti.uim
adb shell pm uninstall -k --user 0 com.sprint.ce.updater
adb shell pm uninstall -k --user 0 com.sprint.ms.cdm
adb shell pm uninstall -k --user 0 com.sprint.ms.smf.services
adb shell pm uninstall -k --user 0 com.sprint.w.installer
adb shell pm uninstall -k --user 0 com.tmobile.m1
adb shell pm uninstall -k --user 0 com.tmobile.pr.mytmobile