
adb shell cmd package install-existing android.autoinstalls.config.lge.cct
adb shell cmd package install-existing com.android.LGSetupWizard
adb shell cmd package install-existing com.android.backupconfirm
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.calllogbackup
adb shell cmd package install-existing com.android.carrierconfig
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.companiondevicemanager
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.gallery3d
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.tgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.htmlviewer
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.printspooler
adb shell cmd package install-existing com.android.providers.blockednumber
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.crucialsoft.asm
adb shell cmd package install-existing com.crucialsoft.fido.client
adb shell cmd package install-existing com.crucialtec.uaf
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.docs.editors.docs
adb shell cmd package install-existing com.google.android.apps.docs.editors.sheets
adb shell cmd package install-existing com.google.android.apps.docs.editors.slides
adb shell cmd package install-existing com.google.android.apps.nbu.files
adb shell cmd package install-existing com.google.android.apps.photos
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.turbo
adb shell cmd package install-existing com.google.android.apps.wellbeing
adb shell cmd package install-existing com.google.android.apps.work.oobconfig
adb shell cmd package install-existing com.google.android.apps.youtube.music
adb shell cmd package install-existing com.google.android.backuptransport
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.gm
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.marvin.talkback
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.ipsec.profile
adb shell cmd package install-existing com.ipsec.service
adb shell cmd package install-existing com.ipsec.vpnclient
adb shell cmd package install-existing com.lge.LGSetupView
adb shell cmd package install-existing com.lge.android.atservice
adb shell cmd package install-existing com.lge.appbox.client
adb shell cmd package install-existing com.lge.appbox.installer
adb shell cmd package install-existing com.lge.bnr
adb shell cmd package install-existing com.lge.camera.sticker.res
adb shell cmd package install-existing com.lge.cic.eden.service
adb shell cmd package install-existing com.lge.cloudhub
adb shell cmd package install-existing com.lge.diag
adb shell cmd package install-existing com.lge.diag.echolocate
adb shell cmd package install-existing com.lge.effect
adb shell cmd package install-existing com.lge.ellievision
adb shell cmd package install-existing com.lge.entitlementcheckservice
adb shell cmd package install-existing com.lge.eula
adb shell cmd package install-existing com.lge.eulaprovider
adb shell cmd package install-existing com.lge.gallery.collagewallpaper
adb shell cmd package install-existing com.lge.gallery.vr.wallpaper
adb shell cmd package install-existing com.lge.gametuner
adb shell cmd package install-existing com.lge.gcuv
adb shell cmd package install-existing com.lge.gdec.client
adb shell cmd package install-existing com.lge.gnss.airtest
adb shell cmd package install-existing com.lge.gnsslogsetting
adb shell cmd package install-existing com.lge.gnsspostest
adb shell cmd package install-existing com.lge.gnsstest
adb shell cmd package install-existing com.lge.hifirecorder
adb shell cmd package install-existing com.lge.hotspotprovision
adb shell cmd package install-existing com.lge.ia.task.informant
adb shell cmd package install-existing com.lge.ia.task.smartcare
adb shell cmd package install-existing com.lge.icecontacts
adb shell cmd package install-existing com.lge.ime
adb shell cmd package install-existing com.lge.ime.solution.handwriting
adb shell cmd package install-existing com.lge.ime.solution.text
adb shell cmd package install-existing com.lge.ime.solution.tshanja
adb shell cmd package install-existing com.lge.laot
adb shell cmd package install-existing com.lge.launcher2.theme.optimus
adb shell cmd package install-existing com.lge.leccp
adb shell cmd package install-existing com.lge.lgcontentsetting
adb shell cmd package install-existing com.lge.lgfota.permission
adb shell cmd package install-existing com.lge.lgmapui
adb shell cmd package install-existing com.lge.lgworld
adb shell cmd package install-existing com.lge.phonemanagement
adb shell cmd package install-existing com.lge.privacylock
adb shell cmd package install-existing com.lge.qlens
adb shell cmd package install-existing com.lge.qmemoplus
adb shell cmd package install-existing com.lge.quicktools
adb shell cmd package install-existing com.lge.rctprovider
adb shell cmd package install-existing com.lge.servicemenu
adb shell cmd package install-existing com.lge.sizechangable.weather
adb shell cmd package install-existing com.lge.sizechangable.weather.platform
adb shell cmd package install-existing com.lge.sizechangable.weather.theme.optimus
adb shell cmd package install-existing com.lge.smartdoctor.webview
adb shell cmd package install-existing com.lge.smartenabler
adb shell cmd package install-existing com.lge.smartshare
adb shell cmd package install-existing com.lge.smartshare.provider
adb shell cmd package install-existing com.lge.smartsharepush
adb shell cmd package install-existing com.lge.springcleaning
adb shell cmd package install-existing com.lge.srtc
adb shell cmd package install-existing com.lge.sui.widget
adb shell cmd package install-existing com.lge.sync
adb shell cmd package install-existing com.lge.systemservice
adb shell cmd package install-existing com.lge.ticntool
adb shell cmd package install-existing com.lge.updatecenter
adb shell cmd package install-existing com.lge.video.vr.wallpaper
adb shell cmd package install-existing com.lge.videostudio
adb shell cmd package install-existing com.lge.vrplayer
adb shell cmd package install-existing com.lge.wifihotspotwidget
adb shell cmd package install-existing com.qualcomm.qcrilmsgtunnel
adb shell cmd package install-existing com.qualcomm.qti.dynamicddsservice
adb shell cmd package install-existing com.qualcomm.qti.poweroffalarm
adb shell cmd package install-existing com.qualcomm.qti.qmmi
adb shell cmd package install-existing com.qualcomm.qti.qms.service.trustzoneaccess
adb shell cmd package install-existing com.qualcomm.qti.remoteSimlockAuth
adb shell cmd package install-existing com.qualcomm.qti.uim
adb shell cmd package install-existing com.sprint.ce.updater
adb shell cmd package install-existing com.sprint.ms.cdm
adb shell cmd package install-existing com.sprint.ms.smf.services
adb shell cmd package install-existing com.sprint.w.installer
adb shell cmd package install-existing com.tmobile.m1
adb shell cmd package install-existing com.tmobile.pr.mytmobile