adb shell pm uninstall --user 0 android.autoinstalls.config.oneplus
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.android.carrierdefaultapp
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.android.dynsystem
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall --user 0 com.android.managedprovisioning
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.android.stk
adb shell pm uninstall --user 0 com.android.traceur
adb shell pm uninstall --user 0 com.coloros.assistantscreen
adb shell pm uninstall --user 0 com.coloros.childrenspace
adb shell pm uninstall --user 0 com.coloros.floatassistant
adb shell pm uninstall --user 0 com.coloros.operationManual
adb shell pm uninstall --user 0 com.coloros.scenemode
adb shell pm uninstall --user 0 com.coloros.smartsidebar
adb shell pm uninstall --user 0 com.coloros.systemclone
adb shell pm uninstall --user 0 com.google.android.adservices.api
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall --user 0 com.google.android.apps.nbu.files
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.google.android.apps.restore
adb shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.ar.lens
adb shell pm uninstall --user 0 com.google.mainline.adservices
adb shell pm uninstall --user 0 com.google.mainline.telemetry
adb shell pm uninstall --user 0 com.heytap.accessory
adb shell pm uninstall --user 0 com.heytap.mcs
adb shell pm uninstall --user 0 com.mediatek.omacp
adb shell pm uninstall --user 0 com.netflix.mediaclient
adb shell pm uninstall --user 0 com.oneplus.account
adb shell pm uninstall --user 0 com.oneplus.membership
adb shell pm uninstall --user 0 com.oplus.appbooster
adb shell pm uninstall --user 0 com.oplus.apprecover
adb shell pm uninstall --user 0 com.oplus.atlas
adb shell pm uninstall --user 0 com.oplus.bttestmode
adb shell pm uninstall --user 0 com.oplus.crashbox
adb shell pm uninstall --user 0 com.oplus.eid
adb shell pm uninstall --user 0 com.oplus.encryption
adb shell pm uninstall --user 0 com.oplus.games
adb shell pm uninstall --user 0 com.oplus.healthservice
adb shell pm uninstall --user 0 com.oplus.interconnectcollectkit
adb shell pm uninstall --user 0 com.oplus.linker
adb shell pm uninstall --user 0 com.oplus.location
adb shell pm uninstall --user 0 com.oplus.locationproxy
adb shell pm uninstall --user 0 com.oplus.logkit
adb shell pm uninstall --user 0 com.oplus.melody
adb shell pm uninstall --user 0 com.oplus.metis
adb shell pm uninstall --user 0 com.oplus.multiapp
adb shell pm uninstall --user 0 com.oplus.nas
adb shell pm uninstall --user 0 com.oplus.nhs
adb shell pm uninstall --user 0 com.oplus.ocloud
adb shell pm uninstall --user 0 com.oplus.ocs
adb shell pm uninstall --user 0 com.oplus.olc
adb shell pm uninstall --user 0 com.oplus.onet
adb shell pm uninstall --user 0 com.oplus.onetrace
adb shell pm uninstall --user 0 com.oplus.portrait
adb shell pm uninstall --user 0 com.oplus.postmanservice
adb shell pm uninstall --user 0 com.oplus.qualityprotect
adb shell pm uninstall --user 0 com.oplus.safecenter
adb shell pm uninstall --user 0 com.oplus.sauhelper
adb shell pm uninstall --user 0 com.oplus.securitypermission
adb shell pm uninstall --user 0 com.oplus.statistics.rom
adb shell pm uninstall --user 0 com.oplus.synergy
adb shell pm uninstall --user 0 com.oplus.virtualcomm
adb shell pm uninstall --user 0 com.oppo.quicksearchbox
adb shell pm uninstall --user 0 com.qti.dcf
adb shell pm uninstall --user 0 com.qualcomm.qti.remoteSimlockAuth
adb shell pm uninstall --user 0 com.qualcomm.qti.uim
adb shell pm uninstall --user 0 com.qualcomm.uimremoteclient
adb shell pm uninstall --user 0 com.qualcomm.uimremoteserver
adb shell pm uninstall --user 0 com.ses.entitlement.o2
adb shell pm uninstall --user 0 com.wapi.wapicertmanage
pause