adb shell cmd package install-existing android.autoinstalls.config.oneplus
adb shell cmd package install-existing com.android.backupconfirm
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.bluetoothmidiservice
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.cellbroadcastreceiver
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.htmlviewer
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.android.wallpaper.livepicker
adb shell cmd package install-existing com.android.wallpaperbackup
adb shell cmd package install-existing com.coloros.assistantscreen
adb shell cmd package install-existing com.coloros.childrenspace
adb shell cmd package install-existing com.coloros.colordirectservice
adb shell cmd package install-existing com.coloros.floatassistant
adb shell cmd package install-existing com.coloros.healthcheck
adb shell cmd package install-existing com.coloros.operationManual
adb shell cmd package install-existing com.coloros.scenemode
adb shell cmd package install-existing com.coloros.smartsidebar
adb shell cmd package install-existing com.coloros.systemclone
adb shell cmd package install-existing com.fido.asm
adb shell cmd package install-existing com.fido.uafclient
adb shell cmd package install-existing com.google.android.adservices.api
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.googleassistant
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.setupwizard.searchselector
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.cellbroadcastreceiver
adb shell cmd package install-existing com.google.android.cellbroadcastservice
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.gms.supervision
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.healthconnect.controller
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.projection.gearhead
adb shell cmd package install-existing com.google.android.rkpdapp
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.ar.lens
adb shell cmd package install-existing com.heytap.accessory
adb shell cmd package install-existing com.microsoft.appmanager
adb shell cmd package install-existing com.microsoft.deviceintegrationservice
adb shell cmd package install-existing com.netflix.mediaclient
adb shell cmd package install-existing com.netflix.partner.activation
adb shell cmd package install-existing com.oneplus.account
adb shell cmd package install-existing com.oneplus.membership
adb shell cmd package install-existing com.oplus.aiunit
adb shell cmd package install-existing com.oplus.appbooster
adb shell cmd package install-existing com.oplus.apprecover
adb shell cmd package install-existing com.oplus.bttestmode
adb shell cmd package install-existing com.oplus.cast
adb shell cmd package install-existing com.oplus.crashbox
adb shell cmd package install-existing com.oplus.customize.coreapp
adb shell cmd package install-existing com.oplus.encryption
adb shell cmd package install-existing com.oplus.engineermode
adb shell cmd package install-existing com.oplus.games
adb shell cmd package install-existing com.oplus.healthservice
adb shell cmd package install-existing com.oplus.lfeh
adb shell cmd package install-existing com.oplus.linker
adb shell cmd package install-existing com.oplus.logkit
adb shell cmd package install-existing com.oplus.melody
adb shell cmd package install-existing com.oplus.metis
adb shell cmd package install-existing com.oplus.multiapp
adb shell cmd package install-existing com.oplus.ocloud
adb shell cmd package install-existing com.oplus.portrait
adb shell cmd package install-existing com.oplus.postmanservice
adb shell cmd package install-existing com.oplus.qualityprotect
adb shell cmd package install-existing com.oplus.safecenter
adb shell cmd package install-existing com.oplus.sauhelper
adb shell cmd package install-existing com.oplus.smartengine
adb shell cmd package install-existing com.oplus.statistics.rom
adb shell cmd package install-existing com.oplus.stdsp
adb shell cmd package install-existing com.oplus.synergy
adb shell cmd package install-existing com.oplus.virtualcomm
adb shell cmd package install-existing com.oplus.wifibackuprestore
adb shell cmd package install-existing com.oppo.quicksearchbox
adb shell cmd package install-existing com.qualcomm.qti.performancemode
adb shell cmd package install-existing com.qualcomm.qti.remoteSimlockAuth
adb shell cmd package install-existing com.qualcomm.uimremoteclient
adb shell cmd package install-existing com.qualcomm.uimremoteserver