adb shell cmd package install-existing android.autoinstalls.config.oneplus
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.coloros.assistantscreen
adb shell cmd package install-existing com.coloros.childrenspace
adb shell cmd package install-existing com.coloros.floatassistant
adb shell cmd package install-existing com.coloros.operationManual
adb shell cmd package install-existing com.coloros.scenemode
adb shell cmd package install-existing com.coloros.smartsidebar
adb shell cmd package install-existing com.coloros.systemclone
adb shell cmd package install-existing com.google.android.adservices.api
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.googleassistant
adb shell cmd package install-existing com.google.android.apps.nbu.files
adb shell cmd package install-existing com.google.android.apps.photos
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.setupwizard.searchselector
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.marvin.talkback
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.ar.lens
adb shell cmd package install-existing com.google.mainline.adservices
adb shell cmd package install-existing com.google.mainline.telemetry
adb shell cmd package install-existing com.heytap.accessory
adb shell cmd package install-existing com.heytap.mcs
adb shell cmd package install-existing com.mediatek.omacp
adb shell cmd package install-existing com.netflix.mediaclient
adb shell cmd package install-existing com.oneplus.account
adb shell cmd package install-existing com.oneplus.membership
adb shell cmd package install-existing com.oplus.appbooster
adb shell cmd package install-existing com.oplus.apprecover
adb shell cmd package install-existing com.oplus.atlas
adb shell cmd package install-existing com.oplus.bttestmode
adb shell cmd package install-existing com.oplus.crashbox
adb shell cmd package install-existing com.oplus.eid
adb shell cmd package install-existing com.oplus.encryption
adb shell cmd package install-existing com.oplus.games
adb shell cmd package install-existing com.oplus.healthservice
adb shell cmd package install-existing com.oplus.interconnectcollectkit
adb shell cmd package install-existing com.oplus.linker
adb shell cmd package install-existing com.oplus.location
adb shell cmd package install-existing com.oplus.locationproxy
adb shell cmd package install-existing com.oplus.logkit
adb shell cmd package install-existing com.oplus.melody
adb shell cmd package install-existing com.oplus.metis
adb shell cmd package install-existing com.oplus.multiapp
adb shell cmd package install-existing com.oplus.nas
adb shell cmd package install-existing com.oplus.nhs
adb shell cmd package install-existing com.oplus.ocloud
adb shell cmd package install-existing com.oplus.ocs
adb shell cmd package install-existing com.oplus.olc
adb shell cmd package install-existing com.oplus.onet
adb shell cmd package install-existing com.oplus.onetrace
adb shell cmd package install-existing com.oplus.portrait
adb shell cmd package install-existing com.oplus.postmanservice
adb shell cmd package install-existing com.oplus.qualityprotect
adb shell cmd package install-existing com.oplus.safecenter
adb shell cmd package install-existing com.oplus.sauhelper
adb shell cmd package install-existing com.oplus.securitypermission
adb shell cmd package install-existing com.oplus.statistics.rom
adb shell cmd package install-existing com.oplus.synergy
adb shell cmd package install-existing com.oplus.virtualcomm
adb shell cmd package install-existing com.oppo.quicksearchbox
adb shell cmd package install-existing com.qti.dcf
adb shell cmd package install-existing com.qualcomm.qti.remoteSimlockAuth
adb shell cmd package install-existing com.qualcomm.qti.uim
adb shell cmd package install-existing com.qualcomm.uimremoteclient
adb shell cmd package install-existing com.qualcomm.uimremoteserver
adb shell cmd package install-existing com.ses.entitlement.o2
adb shell cmd package install-existing com.wapi.wapicertmanage
pause