adb shell pm uninstall --user 0 android.autoinstalls.config.oneplus
adb shell pm uninstall --user 0 com.android.backupconfirm
adb shell pm uninstall --user 0 com.android.bips
adb shell pm uninstall --user 0 com.android.bluetoothmidiservice
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.android.carrierdefaultapp
adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.android.cts.ctsshim
adb shell pm uninstall --user 0 com.android.cts.priv.ctsshim
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.android.dynsystem
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall --user 0 com.android.htmlviewer
adb shell pm uninstall --user 0 com.android.managedprovisioning
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.android.stk
adb shell pm uninstall --user 0 com.android.traceur
adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall --user 0 com.android.wallpaperbackup
adb shell pm uninstall --user 0 com.coloros.assistantscreen
adb shell pm uninstall --user 0 com.coloros.childrenspace
adb shell pm uninstall --user 0 com.coloros.colordirectservice
adb shell pm uninstall --user 0 com.coloros.floatassistant
adb shell pm uninstall --user 0 com.coloros.healthcheck
adb shell pm uninstall --user 0 com.coloros.operationManual
adb shell pm uninstall --user 0 com.coloros.scenemode
adb shell pm uninstall --user 0 com.coloros.smartsidebar
adb shell pm uninstall --user 0 com.coloros.systemclone
adb shell pm uninstall --user 0 com.fido.asm
adb shell pm uninstall --user 0 com.fido.uafclient
adb shell pm uninstall --user 0 com.google.android.adservices.api
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall --user 0 com.google.android.apps.restore
adb shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.google.android.cellbroadcastservice
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.gms.supervision
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.healthconnect.controller
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb shell pm uninstall --user 0 com.google.android.rkpdapp
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.ar.lens
adb shell pm uninstall --user 0 com.heytap.accessory
adb shell pm uninstall --user 0 com.microsoft.appmanager
adb shell pm uninstall --user 0 com.microsoft.deviceintegrationservice
adb shell pm uninstall --user 0 com.netflix.mediaclient
adb shell pm uninstall --user 0 com.netflix.partner.activation
adb shell pm uninstall --user 0 com.oneplus.account
adb shell pm uninstall --user 0 com.oneplus.membership
adb shell pm uninstall --user 0 com.oplus.aiunit
adb shell pm uninstall --user 0 com.oplus.appbooster
adb shell pm uninstall --user 0 com.oplus.apprecover
adb shell pm uninstall --user 0 com.oplus.bttestmode
adb shell pm uninstall --user 0 com.oplus.cast
adb shell pm uninstall --user 0 com.oplus.crashbox
adb shell pm uninstall --user 0 com.oplus.customize.coreapp
adb shell pm uninstall --user 0 com.oplus.encryption
adb shell pm uninstall --user 0 com.oplus.engineermode
adb shell pm uninstall --user 0 com.oplus.games
adb shell pm uninstall --user 0 com.oplus.healthservice
adb shell pm uninstall --user 0 com.oplus.lfeh
adb shell pm uninstall --user 0 com.oplus.linker
adb shell pm uninstall --user 0 com.oplus.logkit
adb shell pm uninstall --user 0 com.oplus.melody
adb shell pm uninstall --user 0 com.oplus.metis
adb shell pm uninstall --user 0 com.oplus.multiapp
adb shell pm uninstall --user 0 com.oplus.ocloud
adb shell pm uninstall --user 0 com.oplus.portrait
adb shell pm uninstall --user 0 com.oplus.postmanservice
adb shell pm uninstall --user 0 com.oplus.qualityprotect
adb shell pm uninstall --user 0 com.oplus.safecenter
adb shell pm uninstall --user 0 com.oplus.sauhelper
adb shell pm uninstall --user 0 com.oplus.smartengine
adb shell pm uninstall --user 0 com.oplus.statistics.rom
adb shell pm uninstall --user 0 com.oplus.stdsp
adb shell pm uninstall --user 0 com.oplus.synergy
adb shell pm uninstall --user 0 com.oplus.virtualcomm
adb shell pm uninstall --user 0 com.oplus.wifibackuprestore
adb shell pm uninstall --user 0 com.oppo.quicksearchbox
adb shell pm uninstall --user 0 com.qualcomm.qti.performancemode
adb shell pm uninstall --user 0 com.qualcomm.qti.remoteSimlockAuth
adb shell pm uninstall --user 0 com.qualcomm.uimremoteclient
adb shell pm uninstall --user 0 com.qualcomm.uimremoteserver