adb shell cmd package install-existing android.auto_generated_rro_product__
adb shell cmd package install-existing android.auto_generated_rro_vendor__
adb shell cmd package install-existing android.autoinstalls.config.samsung
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.calllogbackup
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.chrome
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.theme.font.notoserifsource xxxxxx
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.android.wallpaperbackup
adb shell cmd package install-existing com.facebook.appmanager
adb shell cmd package install-existing com.facebook.services
adb shell cmd package install-existing com.facebook.system
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.subscriptions.red
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.turbo 
adb shell cmd package install-existing com.google.android.cellbroadcastreceiver
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.google.mainline.adservices
adb shell cmd package install-existing com.metropcs.metrozone
adb shell cmd package install-existing com.microsoft.appmanager
adb shell cmd package install-existing com.microsoft.skydrive
adb shell cmd package install-existing com.nuance.nmc.sihome.metropcs
adb shell cmd package install-existing com.osp.app.signin
adb shell cmd package install-existing com.samsung.InputEventApp
adb shell cmd package install-existing com.samsung.SMT
adb shell cmd package install-existing com.samsung.android.app.appsedge
adb shell cmd package install-existing com.samsung.android.app.cocktailbarservice
adb shell cmd package install-existing com.samsung.android.app.parentalcare
adb shell cmd package install-existing com.samsung.android.app.reminder
adb shell cmd package install-existing com.samsung.android.app.routines
adb shell cmd package install-existing com.samsung.android.app.settings.bixby
adb shell cmd package install-existing com.samsung.android.app.taskedge
adb shell cmd package install-existing com.samsung.android.app.updatecenter
adb shell cmd package install-existing com.samsung.android.app.watchmanagerstub
adb shell cmd package install-existing com.samsung.android.bbc.bbcagent
adb shell cmd package install-existing com.samsung.android.bixby.agent
adb shell cmd package install-existing com.samsung.android.bixby.wakeup
adb shell cmd package install-existing com.samsung.android.bixbyvision.framework
adb shell cmd package install-existing com.samsung.android.cidmanager
adb shell cmd package install-existing com.samsung.android.coldwalletservice
adb shell cmd package install-existing com.samsung.android.dqagent
adb shell cmd package install-existing com.samsung.android.dsms
adb shell cmd package install-existing com.samsung.android.easysetup
adb shell cmd package install-existing com.samsung.android.fmm
adb shell cmd package install-existing com.samsung.android.forest
adb shell cmd package install-existing com.samsung.android.game.gamehome
adb shell cmd package install-existing com.samsung.android.game.gametools
adb shell cmd package install-existing com.samsung.android.gru
adb shell cmd package install-existing com.samsung.android.hdmapp
adb shell cmd package install-existing com.samsung.android.inputshare
adb shell cmd package install-existing com.samsung.android.kidsinstaller
adb shell cmd package install-existing com.samsung.android.knox.analytics.uploader
adb shell cmd package install-existing com.samsung.android.knox.pushmanager
adb shell cmd package install-existing com.samsung.android.mcfds
adb shell cmd package install-existing com.samsung.android.mcfserver
adb shell cmd package install-existing com.samsung.android.mdecservice
adb shell cmd package install-existing com.samsung.android.mdm
adb shell cmd package install-existing com.samsung.android.mdx
adb shell cmd package install-existing com.samsung.android.mdx.kit
adb shell cmd package install-existing com.samsung.android.mdx.quickboard
adb shell cmd package install-existing com.samsung.android.net.wifi.wifiguider
adb shell cmd package install-existing com.samsung.android.privateshare
adb shell cmd package install-existing com.samsung.android.rubin.app
adb shell cmd package install-existing com.samsung.android.samsungpass
adb shell cmd package install-existing com.samsung.android.samsungpassautofill
adb shell cmd package install-existing com.samsung.android.scloud
adb shell cmd package install-existing com.samsung.android.sdm.config
adb shell cmd package install-existing com.samsung.android.service.peoplestripe
adb shell cmd package install-existing com.samsung.android.service.stplatform
adb shell cmd package install-existing com.samsung.android.shortcutbackupservice
adb shell cmd package install-existing com.samsung.android.singletake.service
adb shell cmd package install-existing com.samsung.android.smartface
adb shell cmd package install-existing com.samsung.android.smartmirroring
adb shell cmd package install-existing com.samsung.android.smartsuggestions
adb shell cmd package install-existing com.samsung.android.smartswitchassistant
adb shell cmd package install-existing com.samsung.android.spayfw
adb shell cmd package install-existing com.samsung.android.svcagent
adb shell cmd package install-existing com.samsung.android.themestore
adb shell cmd package install-existing com.samsung.gpuwatchapp
adb shell cmd package install-existing com.samsung.klmsagent
adb shell cmd package install-existing com.samsung.oda.service
adb shell cmd package install-existing com.samsung.safetyinformation
adb shell cmd package install-existing com.samsung.slsi.telephony.silentlogging
adb shell cmd package install-existing com.samsung.storyservice
adb shell cmd package install-existing com.samsung.ucs.agent.ese
adb shell cmd package install-existing com.sec.android.RilServiceModeApp
adb shell cmd package install-existing com.sec.android.app.DataCreate
adb shell cmd package install-existing com.sec.android.app.SecSetupWizard
adb shell cmd package install-existing com.sec.android.app.apex
adb shell cmd package install-existing com.sec.android.app.applinker
adb shell cmd package install-existing com.sec.android.app.billing
adb shell cmd package install-existing com.sec.android.app.chromecustomizations
adb shell cmd package install-existing com.sec.android.app.factorykeystring
adb shell cmd package install-existing com.sec.android.app.hwmoduletest
adb shell cmd package install-existing com.sec.android.app.parser
adb shell cmd package install-existing com.sec.android.app.quicktool
adb shell cmd package install-existing com.sec.android.app.safetyassurance
adb shell cmd package install-existing com.sec.android.app.samsungapps
adb shell cmd package install-existing com.sec.android.app.servicemodeapp
adb shell cmd package install-existing com.sec.android.app.setupwizardlegalprovider
adb shell cmd package install-existing com.sec.android.app.wlantest
adb shell cmd package install-existing com.sec.android.daemonapp
adb shell cmd package install-existing com.sec.android.diagmonagent
adb shell cmd package install-existing com.sec.android.easyMover.Agent
adb shell cmd package install-existing com.sec.android.iaft
adb shell cmd package install-existing com.sec.android.mimage.avatarstickers
adb shell cmd package install-existing com.sec.android.soagent
adb shell cmd package install-existing com.sec.android.widgetapp.easymodecontactswidget
adb shell cmd package install-existing com.sec.enterprise.knox.cloudmdm.smdms
adb shell cmd package install-existing com.sec.enterprise.mdm.services.simpin
adb shell cmd package install-existing com.sec.epdgtestapp
adb shell cmd package install-existing com.sec.factory.camera
adb shell cmd package install-existing com.sec.imslogger
adb shell cmd package install-existing com.sec.mhs.smarttethering
adb shell cmd package install-existing com.sec.modem.settings
adb shell cmd package install-existing com.sec.providers.assisteddialing
adb shell cmd package install-existing com.sec.spp.push
adb shell cmd package install-existing com.sec.sve
adb shell cmd package install-existing com.sem.factoryapp