adb shell cmd package install-existing android.auto_generated_rro_product__
adb shell cmd package install-existing android.auto_generated_rro_vendor__
adb shell cmd package install-existing android.autoinstalls.config.samsung
adb shell cmd package install-existing com.android.backupconfirm
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.htmlviewer
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.stk2
adb shell cmd package install-existing com.android.theme.font.notoserifsource
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.diotek.sec.lookup.dictionary
adb shell cmd package install-existing com.facebook.appmanager
adb shell cmd package install-existing com.facebook.services
adb shell cmd package install-existing com.facebook.system
adb shell cmd package install-existing com.google.android.apps.accessibility.voiceaccess
adb shell cmd package install-existing com.google.android.apps.carrier.carrierwifi
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.subscriptions.red
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.turbo
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.gms.supervision
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.hiya.star
adb shell cmd package install-existing com.ironsrc.aura.tmo
adb shell cmd package install-existing com.knox.vpn.proxyhandler
adb shell cmd package install-existing com.metropcs.metrozone
adb shell cmd package install-existing com.microsoft.appmanager
adb shell cmd package install-existing com.microsoft.skydrive
adb shell cmd package install-existing com.monotype.android.font.foundation
adb shell cmd package install-existing com.monotype.android.font.samsungone
adb shell cmd package install-existing com.nuance.nmc.sihome.metropcs
adb shell cmd package install-existing com.osp.app.signin
adb shell cmd package install-existing com.samsung.InputEventApp
adb shell cmd package install-existing com.samsung.SMT
adb shell cmd package install-existing com.samsung.aasaservice
adb shell cmd package install-existing com.samsung.android.aircommandmanager
adb shell cmd package install-existing com.samsung.android.allshare.service.mediashare
adb shell cmd package install-existing com.samsung.android.app.appsedge
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell cmd package install-existing com.samsung.android.app.clipboardedge
adb shell cmd package install-existing com.samsung.android.app.cocktailbarservice
adb shell cmd package install-existing com.samsung.android.app.galaxyfinder
adb shell cmd package install-existing com.samsung.android.app.omcagent
adb shell cmd package install-existing com.samsung.android.app.parentalcare
adb shell cmd package install-existing com.samsung.android.app.reminder
adb shell cmd package install-existing com.samsung.android.app.routines
adb shell cmd package install-existing com.samsung.android.app.settings.bixby
adb shell cmd package install-existing com.samsung.android.app.sharelive
adb shell cmd package install-existing com.samsung.android.app.taskedge
adb shell cmd package install-existing com.samsung.android.app.updatecenter
adb shell cmd package install-existing com.samsung.android.app.watchmanagerstub
adb shell cmd package install-existing com.samsung.android.appseparation
adb shell cmd package install-existing com.samsung.android.ardrawing
adb shell cmd package install-existing com.samsung.android.aremoji
adb shell cmd package install-existing com.samsung.android.aremojieditor
adb shell cmd package install-existing com.samsung.android.audiomirroring
adb shell cmd package install-existing com.samsung.android.authfw
adb shell cmd package install-existing com.samsung.android.aware.service
adb shell cmd package install-existing com.samsung.android.bbc.bbcagent
adb shell cmd package install-existing com.samsung.android.beaconmanager
adb shell cmd package install-existing com.samsung.android.bixby.agent
adb shell cmd package install-existing com.samsung.android.bixby.wakeup
adb shell cmd package install-existing com.samsung.android.bixbyvision.framework
adb shell cmd package install-existing com.samsung.android.cidmanager
adb shell cmd package install-existing com.samsung.android.cmfa.framework
adb shell cmd package install-existing com.samsung.android.coldwalletservice
adb shell cmd package install-existing com.samsung.android.container
adb shell cmd package install-existing com.samsung.android.dqagent
adb shell cmd package install-existing com.samsung.android.dsms
adb shell cmd package install-existing com.samsung.android.easysetup
adb shell cmd package install-existing com.samsung.android.fast
adb shell cmd package install-existing com.samsung.android.fmm
adb shell cmd package install-existing com.samsung.android.forest
adb shell cmd package install-existing com.samsung.android.game.gamehome
adb shell cmd package install-existing com.samsung.android.game.gametools
adb shell cmd package install-existing com.samsung.android.gru
adb shell cmd package install-existing com.samsung.android.hdmapp
adb shell cmd package install-existing com.samsung.android.inputshare
adb shell cmd package install-existing com.samsung.android.ipsgeofence
adb shell cmd package install-existing com.samsung.android.kidsinstaller
adb shell cmd package install-existing com.samsung.android.knox.analytics.uploader
adb shell cmd package install-existing com.samsung.android.knox.attestation
adb shell cmd package install-existing com.samsung.android.knox.containercore
adb shell cmd package install-existing com.samsung.android.knox.kpecore
adb shell cmd package install-existing com.samsung.android.knox.pushmanager
adb shell cmd package install-existing com.samsung.android.location
adb shell cmd package install-existing com.samsung.android.mcfds
adb shell cmd package install-existing com.samsung.android.mcfserver
adb shell cmd package install-existing com.samsung.android.mdecservice
adb shell cmd package install-existing com.samsung.android.mdm
adb shell cmd package install-existing com.samsung.android.mdx
adb shell cmd package install-existing com.samsung.android.mdx.kit
adb shell cmd package install-existing com.samsung.android.mdx.quickboard
adb shell cmd package install-existing com.samsung.android.mobileservice
adb shell cmd package install-existing com.samsung.android.net.wifi.wifiguider
adb shell cmd package install-existing com.samsung.android.oneconnect
adb shell cmd package install-existing com.samsung.android.peripheral.framework
adb shell cmd package install-existing com.samsung.android.privateshare
adb shell cmd package install-existing com.samsung.android.providers.factory
adb shell cmd package install-existing com.samsung.android.rubin.app
adb shell cmd package install-existing com.samsung.android.samsungpass
adb shell cmd package install-existing com.samsung.android.samsungpassautofill
adb shell cmd package install-existing com.samsung.android.samsungpositioning
adb shell cmd package install-existing com.samsung.android.scloud
adb shell cmd package install-existing com.samsung.android.scpm
adb shell cmd package install-existing com.samsung.android.scs
adb shell cmd package install-existing com.samsung.android.scs
adb shell cmd package install-existing com.samsung.android.server.wifi.mobilewips
adb shell cmd package install-existing com.samsung.android.service.peoplestripe
adb shell cmd package install-existing com.samsung.android.service.stplatform
adb shell cmd package install-existing com.samsung.android.service.tagservice
adb shell cmd package install-existing com.samsung.android.shortcutbackupservice
adb shell cmd package install-existing com.samsung.android.singletake.service
adb shell cmd package install-existing com.samsung.android.smartmirroring
adb shell cmd package install-existing com.samsung.android.smartsuggestions
adb shell cmd package install-existing com.samsung.android.smartswitchassistant
adb shell cmd package install-existing com.samsung.android.spayfw
adb shell cmd package install-existing com.samsung.android.stickercenter
adb shell cmd package install-existing com.samsung.android.sume.nn.service
adb shell cmd package install-existing com.samsung.android.themestore
adb shell cmd package install-existing com.samsung.android.visionintelligence
adb shell cmd package install-existing com.samsung.android.visualars
adb shell cmd package install-existing com.samsung.clipboardsaveservice
adb shell cmd package install-existing com.samsung.cmh
adb shell cmd package install-existing com.samsung.gpuwatchapp
adb shell cmd package install-existing com.samsung.ipservice
adb shell cmd package install-existing com.samsung.klmsagent
adb shell cmd package install-existing com.samsung.oda.service
adb shell cmd package install-existing com.samsung.safetyinformation
adb shell cmd package install-existing com.samsung.sait.sohservice
adb shell cmd package install-existing com.samsung.sec.android.teegris.tui_service
adb shell cmd package install-existing com.samsung.slsi.telephony.silentlogging
adb shell cmd package install-existing com.samsung.storyservice
adb shell cmd package install-existing com.samsung.ucs.agent.ese
adb shell cmd package install-existing com.sec.android.CcInfo
adb shell cmd package install-existing com.sec.android.Ccinfo
adb shell cmd package install-existing com.sec.android.RilServiceModeApp
adb shell cmd package install-existing com.sec.android.app.DataCreate
adb shell cmd package install-existing com.sec.android.app.SecSetupWizard
adb shell cmd package install-existing com.sec.android.app.SetupWizard
adb shell cmd package install-existing com.sec.android.app.applinker
adb shell cmd package install-existing com.sec.android.app.billing
adb shell cmd package install-existing com.sec.android.app.hwmoduletest
adb shell cmd package install-existing com.sec.android.app.magnifier
adb shell cmd package install-existing com.sec.android.app.parser
adb shell cmd package install-existing com.sec.android.app.quicktool
adb shell cmd package install-existing com.sec.android.app.samsungapps
adb shell cmd package install-existing com.sec.android.app.servicemodeapp
adb shell cmd package install-existing com.sec.android.app.setupwizard
adb shell cmd package install-existing com.sec.android.app.setupwizardlegalprovider
adb shell cmd package install-existing com.sec.android.app.volumemonitorprovider
adb shell cmd package install-existing com.sec.android.app.wlantest
adb shell cmd package install-existing com.sec.android.autodoodle.service
adb shell cmd package install-existing com.sec.android.diagmonagent
adb shell cmd package install-existing com.sec.android.easyMover.Agent
adb shell cmd package install-existing com.sec.android.mimage.avatarstickers
adb shell cmd package install-existing com.sec.android.provider.badge
adb shell cmd package install-existing com.sec.android.sdhms
adb shell cmd package install-existing com.sec.android.soagent
adb shell cmd package install-existing com.sec.app.RilErrorNotifier
adb shell cmd package install-existing com.sec.enterprise.knox.attestation
adb shell cmd package install-existing com.sec.enterprise.knox.cloudmdm.smdms
adb shell cmd package install-existing com.sec.enterprise.mdm.services.simpin
adb shell cmd package install-existing com.sec.epdgtestapp
adb shell cmd package install-existing com.sec.facatfunction
adb shell cmd package install-existing com.sec.factory.camera
adb shell cmd package install-existing com.sec.hiddenmenu
adb shell cmd package install-existing com.sec.imslogger
adb shell cmd package install-existing com.sec.imsservice
adb shell cmd package install-existing com.sec.location.nfwlocationprivacy
adb shell cmd package install-existing com.sec.location.nsflp2
adb shell cmd package install-existing com.sec.mhs.smarttethering
adb shell cmd package install-existing com.sec.modem.settings
adb shell cmd package install-existing com.sec.providers.assisteddialing
adb shell cmd package install-existing com.sec.samsung.advp.imssettings
adb shell cmd package install-existing com.sec.samsung.advp.imssettings
adb shell cmd package install-existing com.sec.spp.push
adb shell cmd package install-existing com.sec.sprextension
adb shell cmd package install-existing com.sem.factoryapp
adb shell cmd package install-existing com.skms.android.agent
adb shell cmd package install-existing com.test.LTEfunctionality
adb shell cmd package install-existing com.tmobile.dm.cm
adb shell cmd package install-existing com.tmobile.dm.ms.services
adb shell cmd package install-existing com.tmobile.pr.adapt
adb shell cmd package install-existing com.wssyncmldm