adb shell cmd package install-existing --user 0 android.autoinstalls.config.samsung
adb shell cmd package install-existing --user 0 com.android.backupconfirm
adb shell cmd package install-existing --user 0 com.android.bips
adb shell cmd package install-existing --user 0 com.android.bookmarkprovider
adb shell cmd package install-existing --user 0 com.android.carrierdefaultapp
adb shell cmd package install-existing --user 0 com.android.cts.ctsshim
adb shell cmd package install-existing --user 0 com.android.cts.priv.ctsshim
adb shell cmd package install-existing --user 0 com.android.dreams.basic
adb shell cmd package install-existing --user 0 com.android.dynsystem
adb shell cmd package install-existing --user 0 com.android.egg
adb shell cmd package install-existing --user 0 com.android.htmlviewer
adb shell cmd package install-existing --user 0 com.android.managedprovisioning
adb shell cmd package install-existing --user 0 com.android.printspooler
adb shell cmd package install-existing --user 0 com.android.providers.partnerbookmarks
adb shell cmd package install-existing --user 0 com.android.rkpdapp
adb shell cmd package install-existing --user 0 com.android.stk
adb shell cmd package install-existing --user 0 com.android.stk2
adb shell cmd package install-existing --user 0 com.android.theme.font.notoserifsource
adb shell cmd package install-existing --user 0 com.android.traceur
adb shell cmd package install-existing --user 0 com.diotek.sec.lookup.dictionary
adb shell cmd package install-existing --user 0 com.facebook.appmanager
adb shell cmd package install-existing --user 0 com.facebook.services
adb shell cmd package install-existing --user 0 com.facebook.system
adb shell cmd package install-existing --user 0 com.google.android.apps.carrier.carrierwifi
adb shell cmd package install-existing --user 0 com.google.android.apps.restore
adb shell cmd package install-existing --user 0 com.google.android.apps.subscriptions.red
adb shell cmd package install-existing --user 0 com.google.android.apps.tachyon
adb shell cmd package install-existing --user 0 com.google.android.apps.turbo
adb shell cmd package install-existing --user 0 com.google.android.feedback
adb shell cmd package install-existing --user 0 com.google.android.healthconnect.controller
adb shell cmd package install-existing --user 0 com.google.android.onetimeinitializer
adb shell cmd package install-existing --user 0 com.google.android.partnersetup
adb shell cmd package install-existing --user 0 com.google.android.printservice.recommendation
adb shell cmd package install-existing --user 0 com.google.android.setupwizard
adb shell cmd package install-existing --user 0 com.hiya.star
adb shell cmd package install-existing --user 0 com.ironsrc.aura.tmo
adb shell cmd package install-existing --user 0 com.metropcs.metrozone
adb shell cmd package install-existing --user 0 com.microsoft.appmanager
adb shell cmd package install-existing --user 0 com.microsoft.skydrive
adb shell cmd package install-existing --user 0 com.monotype.android.font.foundation
adb shell cmd package install-existing --user 0 com.monotype.android.font.samsungone
adb shell cmd package install-existing --user 0 com.nuance.nmc.sihome.metropcs
adb shell cmd package install-existing --user 0 com.osp.app.signin
adb shell cmd package install-existing --user 0 com.samsung.InputEventApp
adb shell cmd package install-existing --user 0 com.samsung.SMT
adb shell cmd package install-existing --user 0 com.samsung.aasaservice
adb shell cmd package install-existing --user 0 com.samsung.android.aircommandmanager
adb shell cmd package install-existing --user 0 com.samsung.android.allshare.service.mediashare
adb shell cmd package install-existing --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell cmd package install-existing --user 0 com.samsung.android.app.clipboardedge
adb shell cmd package install-existing --user 0 com.samsung.android.app.omcagent
adb shell cmd package install-existing --user 0 com.samsung.android.app.parentalcare
adb shell cmd package install-existing --user 0 com.samsung.android.app.reminder
adb shell cmd package install-existing --user 0 com.samsung.android.app.routines
adb shell cmd package install-existing --user 0 com.samsung.android.app.taskedge
adb shell cmd package install-existing --user 0 com.samsung.android.app.updatecenter
adb shell cmd package install-existing --user 0 com.samsung.android.app.watchmanagerstub
adb shell cmd package install-existing --user 0 com.samsung.android.appseparation
adb shell cmd package install-existing --user 0 com.samsung.android.aremoji
adb shell cmd package install-existing --user 0 com.samsung.android.aremojieditor
adb shell cmd package install-existing --user 0 com.samsung.android.audiomirroring
adb shell cmd package install-existing --user 0 com.samsung.android.authfw
adb shell cmd package install-existing --user 0 com.samsung.android.bbc.bbcagent
adb shell cmd package install-existing --user 0 com.samsung.android.beaconmanager
adb shell cmd package install-existing --user 0 com.samsung.android.bixby.agent
adb shell cmd package install-existing --user 0 com.samsung.android.bixby.wakeup
adb shell cmd package install-existing --user 0 com.samsung.android.bixbyvision.framework
adb shell cmd package install-existing --user 0 com.samsung.android.callbgprovider
adb shell cmd package install-existing --user 0 com.samsung.android.cidmanager
adb shell cmd package install-existing --user 0 com.samsung.android.coldwalletservice
adb shell cmd package install-existing --user 0 com.samsung.android.container
adb shell cmd package install-existing --user 0 com.samsung.android.dqagent
adb shell cmd package install-existing --user 0 com.samsung.android.dsms
adb shell cmd package install-existing --user 0 com.samsung.android.easysetup
adb shell cmd package install-existing --user 0 com.samsung.android.emergency
adb shell cmd package install-existing --user 0 com.samsung.android.fast
adb shell cmd package install-existing --user 0 com.samsung.android.forest
adb shell cmd package install-existing --user 0 com.samsung.android.game.gamehome
adb shell cmd package install-existing --user 0 com.samsung.android.game.gametools
adb shell cmd package install-existing --user 0 com.samsung.android.game.gos
adb shell cmd package install-existing --user 0 com.samsung.android.gru
adb shell cmd package install-existing --user 0 com.samsung.android.hdmapp
adb shell cmd package install-existing --user 0 com.samsung.android.inputshare
adb shell cmd package install-existing --user 0 com.samsung.android.ipsgeofence
adb shell cmd package install-existing --user 0 com.samsung.android.kidsinstaller
adb shell cmd package install-existing --user 0 com.samsung.android.knox.analytics.uploader
adb shell cmd package install-existing --user 0 com.samsung.android.location
adb shell cmd package install-existing --user 0 com.samsung.android.mcfds
adb shell cmd package install-existing --user 0 com.samsung.android.mcfserver
adb shell cmd package install-existing --user 0 com.samsung.android.mdecservice
adb shell cmd package install-existing --user 0 com.samsung.android.mdm
adb shell cmd package install-existing --user 0 com.samsung.android.mobileservice
adb shell cmd package install-existing --user 0 com.samsung.android.net.wifi.wifiguider
adb shell cmd package install-existing --user 0 com.samsung.android.providers.factory
adb shell cmd package install-existing --user 0 com.samsung.android.rampart
adb shell cmd package install-existing --user 0 com.samsung.android.rubin.app
adb shell cmd package install-existing --user 0 com.samsung.android.samsungpass
adb shell cmd package install-existing --user 0 com.samsung.android.samsungpassautofill
adb shell cmd package install-existing --user 0 com.samsung.android.samsungpositioning
adb shell cmd package install-existing --user 0 com.samsung.android.scloud
adb shell cmd package install-existing --user 0 com.samsung.android.scpm
adb shell cmd package install-existing --user 0 com.samsung.android.scs
adb shell cmd package install-existing --user 0 com.samsung.android.service.peoplestripe
adb shell cmd package install-existing --user 0 com.samsung.android.service.stplatform
adb shell cmd package install-existing --user 0 com.samsung.android.service.tagservice
adb shell cmd package install-existing --user 0 com.samsung.android.shortcutbackupservice
adb shell cmd package install-existing --user 0 com.samsung.android.singletake.service
adb shell cmd package install-existing --user 0 com.samsung.android.smartmirroring
adb shell cmd package install-existing --user 0 com.samsung.android.smartsuggestions
adb shell cmd package install-existing --user 0 com.samsung.android.smartswitchassistant
adb shell cmd package install-existing --user 0 com.samsung.android.spayfw
adb shell cmd package install-existing --user 0 com.samsung.android.stickercenter
adb shell cmd package install-existing --user 0 com.samsung.android.themestore
adb shell cmd package install-existing --user 0 com.samsung.android.visionintelligence
adb shell cmd package install-existing --user 0 com.samsung.android.visualars
adb shell cmd package install-existing --user 0 com.samsung.android.widget.pictureframe
adb shell cmd package install-existing --user 0 com.samsung.cmh
adb shell cmd package install-existing --user 0 com.samsung.crane
adb shell cmd package install-existing --user 0 com.samsung.gpuwatchapp
adb shell cmd package install-existing --user 0 com.samsung.ipservice
adb shell cmd package install-existing --user 0 com.samsung.oda.service
adb shell cmd package install-existing --user 0 com.samsung.safetyinformation
adb shell cmd package install-existing --user 0 com.samsung.sait.sohservice
adb shell cmd package install-existing --user 0 com.samsung.sdm
adb shell cmd package install-existing --user 0 com.samsung.slsi.telephony.silentlogging
adb shell cmd package install-existing --user 0 com.samsung.storyservice
adb shell cmd package install-existing --user 0 com.sec.android.CcInfo
adb shell cmd package install-existing --user 0 com.sec.android.RilServiceModeApp
adb shell cmd package install-existing --user 0 com.sec.android.app.SecSetupWizard
adb shell cmd package install-existing --user 0 com.sec.android.app.billing
adb shell cmd package install-existing --user 0 com.sec.android.app.hwmoduletest
adb shell cmd package install-existing --user 0 com.sec.android.app.magnifier
adb shell cmd package install-existing --user 0 com.sec.android.app.parser
adb shell cmd package install-existing --user 0 com.sec.android.app.quicktool
adb shell cmd package install-existing --user 0 com.sec.android.app.safetyassurance
adb shell cmd package install-existing --user 0 com.sec.android.app.samsungapps
adb shell cmd package install-existing --user 0 com.sec.android.app.servicemodeapp
adb shell cmd package install-existing --user 0 com.sec.android.app.setupwizard
adb shell cmd package install-existing --user 0 com.sec.android.app.setupwizardlegalprovider
adb shell cmd package install-existing --user 0 com.sec.android.app.volumemonitorprovider
adb shell cmd package install-existing --user 0 com.sec.android.app.wlantest
adb shell cmd package install-existing --user 0 com.sec.android.autodoodle.service
adb shell cmd package install-existing --user 0 com.sec.android.diagmonagent
adb shell cmd package install-existing --user 0 com.sec.android.easyMover
adb shell cmd package install-existing --user 0 com.sec.android.easyMover.Agent
adb shell cmd package install-existing --user 0 com.sec.android.mimage.avatarstickers
adb shell cmd package install-existing --user 0 com.sec.android.provider.badge
adb shell cmd package install-existing --user 0 com.sec.android.sdhms
adb shell cmd package install-existing --user 0 com.sec.android.soagent
adb shell cmd package install-existing --user 0 com.sec.app.RilErrorNotifier
adb shell cmd package install-existing --user 0 com.sec.epdgtestapp
adb shell cmd package install-existing --user 0 com.sec.facatfunction
adb shell cmd package install-existing --user 0 com.sec.factory.camera
adb shell cmd package install-existing --user 0 com.sec.hiddenmenu
adb shell cmd package install-existing --user 0 com.sec.imslogger
adb shell cmd package install-existing --user 0 com.sec.location.nfwlocationprivacy
adb shell cmd package install-existing --user 0 com.sec.location.nsflp2
adb shell cmd package install-existing --user 0 com.sec.mhs.smarttethering
adb shell cmd package install-existing --user 0 com.sec.modem.settings
adb shell cmd package install-existing --user 0 com.sec.providers.assisteddialing
adb shell cmd package install-existing --user 0 com.sec.spp.push
adb shell cmd package install-existing --user 0 com.sem.factoryapp
adb shell cmd package install-existing --user 0 com.skms.android.agent
adb shell cmd package install-existing --user 0 com.snap.camerakit.plugin.v1
adb shell cmd package install-existing --user 0 com.test.LTEfunctionality
adb shell cmd package install-existing --user 0 com.tmobile.dm.cm
adb shell cmd package install-existing --user 0 com.tmobile.dm.ms.services
adb shell cmd package install-existing --user 0 com.tmobile.pr.adapt
adb shell cmd package install-existing --user 0 com.wssyncmldm