adb shell pm uninstall --user 0 android.autoinstalls.config.oneplus
adb shell pm uninstall --user 0 cn.oneplus.nvbackup
adb shell pm uninstall --user 0 cn.oneplus.oemtcma
adb shell pm uninstall --user 0 cn.oneplus.photos
adb shell pm uninstall --user 0 com.android.backupconfirm
adb shell pm uninstall --user 0 com.android.bluetoothmidiservice
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.android.carrierdefaultapp
adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.android.dynsystem
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall --user 0 com.android.htmlviewer
adb shell pm uninstall --user 0 com.android.localtransport
adb shell pm uninstall --user 0 com.android.managedprovisioning
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.android.sharedstoragebackup
adb shell pm uninstall --user 0 com.android.statementservice
adb shell pm uninstall --user 0 com.android.stk
adb shell pm uninstall --user 0 com.android.traceur
adb shell pm uninstall --user 0 com.dsi.ant.server
adb shell pm uninstall --user 0 com.fingerprints.fingerprintsensortest
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.google.android.apps.restore
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.google.android.apps.turbo
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.oem.autotest
adb shell pm uninstall --user 0 com.oem.logkitsdservice
adb shell pm uninstall --user 0 com.oem.nfc
adb shell pm uninstall --user 0 com.oem.oemlogkit
adb shell pm uninstall --user 0 com.oem.rftoolkit
adb shell pm uninstall --user 0 com.oneplus.account
adb shell pm uninstall --user 0 com.oneplus.appupgrader
adb shell pm uninstall --user 0 com.oneplus.backuprestore.remoteservice
adb shell pm uninstall --user 0 com.oneplus.brickmode
adb shell pm uninstall --user 0 com.oneplus.bttestmode
adb shell pm uninstall --user 0 com.oneplus.carrierlocation
adb shell pm uninstall --user 0 com.oneplus.communication.data
adb shell pm uninstall --user 0 com.oneplus.config
adb shell pm uninstall --user 0 com.oneplus.dataoptimization
adb shell pm uninstall --user 0 com.oneplus.diagnosemanager
adb shell pm uninstall --user 0 com.oneplus.engmode
adb shell pm uninstall --user 0 com.oneplus.factorymode
adb shell pm uninstall --user 0 com.oneplus.filemanager
adb shell pm uninstall --user 0 com.oneplus.gamespace
adb shell pm uninstall --user 0 com.oneplus.geoiptime
adb shell pm uninstall --user 0 com.oneplus.minidumpoptimization
adb shell pm uninstall --user 0 com.oneplus.opbackup
adb shell pm uninstall --user 0 com.oneplus.opbugreportlite
adb shell pm uninstall --user 0 com.oneplus.orm
adb shell pm uninstall --user 0 com.oneplus.security
adb shell pm uninstall --user 0 com.oneplus.ses
adb shell pm uninstall --user 0 com.oneplus.setupwizard
adb shell pm uninstall --user 0 com.oneplus.telephonyoptimization
adb shell pm uninstall --user 0 com.qti.diagservices
adb shell pm uninstall --user 0 com.qti.qualcomm.datastatusnotification
adb shell pm uninstall --user 0 com.qualcomm.embms
adb shell pm uninstall --user 0 com.qualcomm.qti.devicestatisticsservice
adb shell pm uninstall --user 0 com.qualcomm.qti.lpa
adb shell pm uninstall --user 0 com.qualcomm.qti.performancemode
adb shell pm uninstall --user 0 com.qualcomm.qti.qcolor
adb shell pm uninstall --user 0 com.qualcomm.qti.qms.service.telemetry
adb shell pm uninstall --user 0 com.qualcomm.qti.remoteSimlockAuth
adb shell pm uninstall --user 0 com.qualcomm.qti.services.systemhelper
adb shell pm uninstall --user 0 com.qualcomm.qti.uim
adb shell pm uninstall --user 0 com.qualcomm.qti.uimGbaApp
adb shell pm uninstall --user 0 com.qualcomm.qti.workloadclassifier
adb shell pm uninstall --user 0 com.qualcomm.uimremoteclient
adb shell pm uninstall --user 0 com.qualcomm.uimremoteserver
adb shell pm uninstall --user 0 com.tencent.soter.soterserver
adb shell pm uninstall --user 0 net.oneplus.commonlogtool
adb shell pm uninstall --user 0 net.oneplus.odm
adb shell pm uninstall --user 0 net.oneplus.odm.provider
adb shell pm uninstall --user 0 net.oneplus.provider.appcategoryprovider
adb shell pm uninstall --user 0 net.oneplus.push
adb shell pm uninstall --user 0 org.ifaa.aidl.manager