adb shell cmd package install-existing android.autoinstalls.config.oneplus
adb shell cmd package install-existing cn.oneplus.nvbackup
adb shell cmd package install-existing cn.oneplus.oemtcma
adb shell cmd package install-existing cn.oneplus.photos
adb shell cmd package install-existing com.android.backupconfirm
adb shell cmd package install-existing com.android.bluetoothmidiservice
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.carrierdefaultapp
adb shell cmd package install-existing com.android.cellbroadcastreceiver
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dynsystem
adb shell cmd package install-existing com.android.egg
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.htmlviewer
adb shell cmd package install-existing com.android.localtransport
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.sharedstoragebackup
adb shell cmd package install-existing com.android.statementservice
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.dsi.ant.server
adb shell cmd package install-existing com.fingerprints.fingerprintsensortest
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.googleassistant
adb shell cmd package install-existing com.google.android.apps.photos
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.turbo
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.marvin.talkback
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.projection.gearhead
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.oem.autotest
adb shell cmd package install-existing com.oem.logkitsdservice
adb shell cmd package install-existing com.oem.nfc
adb shell cmd package install-existing com.oem.oemlogkit
adb shell cmd package install-existing com.oem.rftoolkit
adb shell cmd package install-existing com.oneplus.account
adb shell cmd package install-existing com.oneplus.appupgrader
adb shell cmd package install-existing com.oneplus.backuprestore.remoteservice
adb shell cmd package install-existing com.oneplus.brickmode
adb shell cmd package install-existing com.oneplus.bttestmode
adb shell cmd package install-existing com.oneplus.carrierlocation
adb shell cmd package install-existing com.oneplus.communication.data
adb shell cmd package install-existing com.oneplus.config
adb shell cmd package install-existing com.oneplus.dataoptimization
adb shell cmd package install-existing com.oneplus.diagnosemanager
adb shell cmd package install-existing com.oneplus.engmode
adb shell cmd package install-existing com.oneplus.factorymode
adb shell cmd package install-existing com.oneplus.filemanager
adb shell cmd package install-existing com.oneplus.gamespace
adb shell cmd package install-existing com.oneplus.geoiptime
adb shell cmd package install-existing com.oneplus.minidumpoptimization
adb shell cmd package install-existing com.oneplus.opbackup
adb shell cmd package install-existing com.oneplus.opbugreportlite
adb shell cmd package install-existing com.oneplus.orm
adb shell cmd package install-existing com.oneplus.security
adb shell cmd package install-existing com.oneplus.ses
adb shell cmd package install-existing com.oneplus.setupwizard
adb shell cmd package install-existing com.oneplus.telephonyoptimization
adb shell cmd package install-existing com.qti.diagservices
adb shell cmd package install-existing com.qti.qualcomm.datastatusnotification
adb shell cmd package install-existing com.qualcomm.embms
adb shell cmd package install-existing com.qualcomm.qti.devicestatisticsservice
adb shell cmd package install-existing com.qualcomm.qti.lpa
adb shell cmd package install-existing com.qualcomm.qti.performancemode
adb shell cmd package install-existing com.qualcomm.qti.qcolor
adb shell cmd package install-existing com.qualcomm.qti.qms.service.telemetry
adb shell cmd package install-existing com.qualcomm.qti.remoteSimlockAuth
adb shell cmd package install-existing com.qualcomm.qti.services.systemhelper
adb shell cmd package install-existing com.qualcomm.qti.uim
adb shell cmd package install-existing com.qualcomm.qti.uimGbaApp
adb shell cmd package install-existing com.qualcomm.qti.workloadclassifier
adb shell cmd package install-existing com.qualcomm.uimremoteclient
adb shell cmd package install-existing com.qualcomm.uimremoteserver
adb shell cmd package install-existing com.tencent.soter.soterserver
adb shell cmd package install-existing net.oneplus.commonlogtool
adb shell cmd package install-existing net.oneplus.odm
adb shell cmd package install-existing net.oneplus.odm.provider
adb shell cmd package install-existing net.oneplus.provider.appcategoryprovider
adb shell cmd package install-existing net.oneplus.push
adb shell cmd package install-existing org.ifaa.aidl.manager